name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"

      # for testing we're also gonna setup bun
      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Run CI
        run: |
          yarn install
          yarn lint
          yarn test
