name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: Run CI
        run: |
          bun run lint
          bun run test
